=== OI4/oi4-oec-service/packages/oi4-oec-json-schemas/src/schemas/NetworkMessage.schema.json
{
  "$id": "NetworkMessage.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of an event",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "MessageId",
    "MessageType",
    "PublisherId",
    "Messages"
  ],
  "$comment": "TODO: oi4identifier needs to be updated and implemented here. NetworkMessageBase was removed, if necessary, we can patch it back in",
  "properties": {
    "CorrelationId": {
      "type": "string",
      "description": "Correlation ID used for logging and as debug information"
    },
    "DataSetClassId": {
      "type": "string",
      "description": "Dataset Class ID",
      "pattern": "^[0-9a-fA-F-]+$"
    },
    "MessageId": {
      "type": "string",
      "description": "Message ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^.{1,}-(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "MessageType": {
      "const": "ua-data",
      "description": "Message Type"
    },
    "PublisherId": {
      "type": "string",
      "description": "Publisher ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "Messages": {
      "type": "array",
      "description": "Messages Array",
      "items": {
        "$ref": "DataSetMessage.schema.json"
      }
    }
  }
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/publicationList_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "217434d6-6e1e-4230-b907-f52bc9ffe152",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 161,
      "Filter": "MAM",
      "Source": "openindustry4.com/nd/nd/nd",
      "Payload": {
        "Resource": "MAM",
        "Source": "openindustry4.com/nd/nd/nd",
        "DataSetWriterId": 1,
        "Mode": "APPLICATION_SOURCE_FILTER_8",
        "Config": "NONE_0"
      }
    }, {
      "DataSetWriterId": 161,
      "Filter": "Health",
      "Source": "openindustry4.com/nd/nd/nd",
      "Payload": {
        "Resource": "Health",
        "Source": "openindustry4.com/nd/nd/nd",
        "DataSetWriterId": 3456,
        "Mode": "APPLICATION_SOURCE_FILTER_8",
        "Interval": 0,
        "Config": "NONE_0"
      }
    }, {
      "DataSetWriterId": 161,
      "Filter": "Profile",
      "Source": "openindustry4.com/nd/nd/nd",
      "Payload": {
        "Resource": "Profile",
        "Source": "openindustry4.com/nd/nd/nd",
        "DataSetWriterId": 74,
        "Mode": "APPLICATION_SOURCE_FILTER_8",
        "Interval": 0,
        "Config": "NONE_0"
      }
    }, {
      "DataSetWriterId": 161,
      "Filter": "Event",
      "Source": "openindustry4.com/nd/nd/nd",
      "Payload": {
        "Resource": "Event",
        "Source": "openindustry4.com/nd/nd/nd",
        "Filter": "Syslog/Notice",
        "DataSetWriterId": 625,
        "Mode": "APPLICATION_2",
        "Interval": 0,
        "Config": "NONE_0"
      }
    }, {
      "DataSetWriterId": 161,
      "Filter": "Data",
      "Source": "openindustry4.com/nd/nd/nd",
      "Payload": {
        "Resource": "Data",
        "Source": "openindustry4.com/nd/nd/nd",
        "Filter": "oee",
        "DataSetWriterId": 93,
        "Mode": "APPLICATION_SOURCE_FILTER_8",
        "Config": "MODE_AND_INTERVAL_3"
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/referenceDesignation_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "27a75019-164a-496d-a38b-90e8a55c2cfa",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 489,
      "Filter": "room_206",
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 17,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Location": {
          "Value": "room_206",
          "Local": "Room 206",
          "Parent": {
            "Value": "floor_2",
            "Local": "Floor 2",
            "Oi4Identifier": "provider.com/FieldDataService/FDS-001/1200-0345"
          }
        }
      }
    }
  ]
}
