=== OI4/oi4-oec-service/packages/oi4-oec-json-schemas/src/schemas/NetworkMessage.schema.json
{
  "$id": "NetworkMessage.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of an event",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "MessageId",
    "MessageType",
    "PublisherId",
    "Messages"
  ],
  "$comment": "TODO: oi4identifier needs to be updated and implemented here. NetworkMessageBase was removed, if necessary, we can patch it back in",
  "properties": {
    "CorrelationId": {
      "type": "string",
      "description": "Correlation ID used for logging and as debug information"
    },
    "DataSetClassId": {
      "type": "string",
      "description": "Dataset Class ID",
      "pattern": "^[0-9a-fA-F-]+$"
    },
    "MessageId": {
      "type": "string",
      "description": "Message ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^.{1,}-(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "MessageType": {
      "const": "ua-data",
      "description": "Message Type"
    },
    "PublisherId": {
      "type": "string",
      "description": "Publisher ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "Messages": {
      "type": "array",
      "description": "Messages Array",
      "items": {
        "$ref": "DataSetMessage.schema.json"
      }
    }
  }
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/mam_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "360ca8f3-5e66-42a2-8f10-9cdf45f4bf58",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 1,
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 4,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Manufacturer": {
          "Locale": "en-US",
          "Text": "OpenIndustry 4"
        },
        "ManufacturerUri": "openindustry4.com",
        "Model": {
          "Locale": "en-US",
          "Text": "OEC Registry"
        },
        "ProductCode": "nd",
        "HardwareRevision": "",
        "SoftwareRevision": "1.0.1",
        "DeviceRevision": "",
        "DeviceManual": "https://openindustry4.com/fileadmin/Dateien/Downloads/2019_11_20_OI4_Whitepaper_General.pdf",
        "DeviceClass": "OI4.Registry",
        "SerialNumber": "nd",
        "ProductInstanceUri": "openindustry4.com/nd/nd/nd",
        "RevisionCounter": 1,
        "Description": {
          "Locale": "en-US",
          "Text": "This is the Registry"
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/interfaces_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "96d22d73-bce6-42d3-9949-45e0d04e4d54",
  "CorrelationId": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [
      {
      "DataSetWriterId": 623,
      "Source": "openindustry4.com/nd/nd/nd",
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {}
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/health_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "d8e7b6df-42ba-448a-975a-199f59e8ffeb",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 3456,
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 57,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Health": "NORMAL_0",
        "HealthScore": 100
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/profile_app_data_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "48017c6a-05c8-48d7-9d85-4b08bbb707f3",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 74,
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 42,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Resources": [
          "MAM",
          "Health",
          "License",
          "LicenseText",
          "Profile",
          "PublicationList",
		      "Data",
		      "Metadata"
        ]
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/licenseText_apache_valid.json
{
  "MessageId": "1577836800001-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "a6e6c727-4057-419f-b2ea-3fe9173e71cf",
  "CorrelationId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 490,
      "Filter": "Apache%202.0",
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 17,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "LicenseText": "This is the Apache 2.0 licence test text"
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/event_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "543ae05e-b6d9-4161-a0a3-350a0fac5976",
  "CorrelationId": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [
    {
      "DataSetWriterId": 623,
      "Filter": "Status/Good",
      "Source": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 14,
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "Number": 0,
        "Description": "The operation succeeded.",
        "category": "CAT_STATUS_1",
        "details": {
          "SymbolicId": "Good"
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-model/test/__fixtures__/mam_network_message.json
{
  "MessageId": "1639693510094-OTConnector/provider.com/FieldDataService/FDS-001/1200-0345",
  "MessageType": "ua-data",
  "PublisherId": "OTConnector/provider.com/FieldDataService/FDS-001/1200-0345",
  "DataSetClassId": "360ca8f3-5e66-42a2-8f10-9cdf45f4bf58",
  "CorrelationId": "1639693510000-ITConnector/consumer.com/MEService/MES%2fOnPrem/Inst07322",
  "Messages": [
    {
      "DataSetWriterId": 1,
      "Source": "provider.com/FieldDataService/FDS-001/1200-0345",
      "SequenceNumber": 4,
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "Manufacturer": {
          "Locale": "en-US",
          "Text": "Provider Ltd."
        },
        "ManufacturerUri": "provider.com",
        "Model": {
          "Locale": "en-US",
          "Text": "FieldDataService"
        },
        "ProductCode": "FDS-001",
        "HardwareRevision": "",
        "SoftwareRevision": "1.0.1",
        "DeviceRevision": "",
        "DeviceManual": "https://provider.com/manuals/FDS-001.pdf",
        "DeviceClass": "OI4.OTConnector",
        "SerialNumber": "1200-0345",
        "ProductInstanceUri": "provider.com/FieldDataService/FDS-001/1200-0345",
        "RevisionCounter": 1,
        "Description": {
          "Locale": "en-US",
          "Text": "This OT connector provides field data"
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-opcua-model/src/__fixtures__/mam_network_message.json
{
  "MessageId": "1647956284200-Registry/hilscher.com/OEC%20Registry/OEC-REG/OI4ARegistryContainerLocal",
  "MessageType": "ua-data",
  "DataSetClassId": "360ca8f3-5e66-42a2-8f10-9cdf45f4bf58",
  "PublisherId": "Registry/hilscher.com/OEC%20Registry/OEC-REG/OI4ARegistryContainerLocal",
  "Messages": [
    {
      "DataSetWriterId": 1,
      "Timestamp": "2022-03-22T13:38:04.200Z",
      "POI": "hilscher.com/OEC%20Registry/OEC-REG/OI4ARegistryContainerLocal",
      "Payload": {
        "Manufacturer": {
          "locale": "en-US",
          "text": "Hilscher"
        },
        "ManufacturerUri": "hilscher.com",
        "Model": {
          "locale": "en-US",
          "text": "OEC Registry"
        },
        "ProductCode": "OEC-REG",
        "HardwareRevision": "",
        "SoftwareRevision": "0.12.1",
        "DeviceRevision": "",
        "DeviceManual": "",
        "DeviceClass": "Registry",
        "SerialNumber": "OI4ARegistryContainerLocal",
        "ProductInstanceUri": "hilscher.com/OEC%20Registry/OEC-REG/OI4ARegistryContainerLocal",
        "RevisionCounter": 0,
        "Description": {
          "locale": "en-US",
          "text": "The OEC Registry, an Open Industry 4.0 Alliance application"
        }
      }
    }
  ],
  "CorrelationId": ""
}
